### ISSUE TITLE
Can't set timezone for CronSchedule

### ISSUE THREAD

**Issue by meum** [fglaeser/Quartz.Extensions.DependencyInjection#6]
Quartz has the ability to specify a timezone for a CronSchedule like this:

`
TriggerBuilder.Create().WithCronSchedule("0 0 8 ? * MON-FRI", x => x.InTimeZone(TimeZoneInfo.FindSystemTimeZoneById("Central European Standard Time")))
`

It would be great if this functionality could be exposed in this library also.

**Comment by fglaeser** [comment]
Hi, You should Open a issue here https://github.com/quartznet/quartznet/issues
