### ISSUE TITLE
ServiceCollectionExtensions will add a regular type AddJob 

### ISSUE THREAD

**Issue by startewho** [fglaeser/Quartz.Extensions.DependencyInjection#7]
When I use a dynamic Job 。usually it write like this 
```
type jobType=xxx;
q.AddJob(jobType,j=>{});
```
Now it use the generic Type 
Thanks for your great work. it works great with the msft 's ioc;

**Comment by fglaeser** [comment]
Hi @startewho, sorry but I didn't understand you, I don't know if it is a question or just a comment, could you be more specific? Thanks!!

**Comment by startewho** [comment]
> Hi @startewho, sorry but I didn't understand you, I don't know if it is a question or just a comment, could you be more specific? Thanks!!

 I have add the pull request in quartz.net rep.it has been merged into the main. Thanks for your great work that supply the ioc feature.
